CREATE TABLE T_UsrPrf (
    UsrPrfCod INTEGER IDENTITY(1,1),
    UsrPrfUsrCod INTEGER,
    UsrPrfCgo VARCHAR(255),
    UsrPrfBio VARCHAR(4000),
    UsrPrfUrl VARCHAR(999),
    UsrPrfFto VARCHAR(255),
    UsrPrfAudIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    UsrPrfAudUpd DATETIME,
    UsrPrfAudDlt DATETIME,
    UsrPrfAudUsr VARCHAR(255),
    CONSTRAINT PK_USRPRF PRIMARY KEY (UsrPrfCod),
    CONSTRAINT FK_USRPRF_01 FOREIGN KEY (UsrPrfUsrCod) REFERENCES T_Usr(UsrCod) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDXUsrPrf01 ON T_UsrPrf (UsrPrfAudIns);
CREATE INDEX IF NOT EXISTS IDXUsrPrf02 ON T_UsrPrf (UsrPrfCgo);
