CREATE TABLE T_Usr_Prf (
    UsrPrfCod INTEGER PRIMARY KEY AUTOINCREMENT,
    UsrPrfUsrCod INTEGER NOT NULL UNIQUE,
    UsrPrfCgo VARCHAR(255),
    UsrPrfBio VARCHAR(4000),
    UsrPrfUrl VARCHAR(999),
    UsrPrFto VARCHAR(255),
    UsrPrfIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    UsrPrfUpd DATETIME,
    UsrPrfDlt DATETIME,
    UsrPrfUsr VARCHAR(255),
    PRIMARY KEY(UsrPrfCod, UsrPrfUsrCod),
    FOREIGN KEY (UsrPrfUsrCod) REFERENCES T_Usr(UsrCod) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDXUsrPrf01 ON T_Usr_Prf (UsrPrfIns);
CREATE INDEX IF NOT EXISTS IDXUsrPrf02 ON T_Usr_Prf (PrfCgo);
