CREATE TABLE IF NOT EXISTS T_USR (
    UsrCod INTEGER,
    UsrNme VARCHAR(255) NOT NULL,
    UsrLgn VARCHAR(255) NOT NULL,
    UsrPwdHash VARCHAR(255) NOT NULL,
    UsrRle VARCHAR(255) NOT NULL DEFAULT 'User',
    UsrAudIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    UsrAudUpd DATETIME,
    UsrAudDlt DATETIME,
    UsrAudUsr VARCHAR(255),
    CONSTRAINT PK_USR PRIMARY KEY (UsrCod),
    CONSTRAINT UQ_USR_UsrLgn UNIQUE (UsrLgn)
);

CREATE INDEX IF NOT EXISTS IDX_USR_01 ON T_USR (UsrAudIns);
CREATE INDEX IF NOT EXISTS IDX_USR_02 ON T_USR (UsrNme);
CREATE INDEX IF NOT EXISTS IDX_USR_03 ON T_USR (UsrRle, UsrNme);

CREATE TABLE IF NOT EXISTS T_DEV (
    DevCod INTEGER,
    DevNme VARCHAR(255) NOT NULL,
    DevLgnExt VARCHAR(255),
    DevCgo VARCHAR(255),
    DevBio VARCHAR(4000),
    DevPgeUrl VARCHAR(999),
    DevFto VARCHAR(255),
    DevAudIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    DevAudUpd DATETIME,
    DevAudDlt DATETIME,
    DevAudUsr VARCHAR(255),
    CONSTRAINT PK_DEV PRIMARY KEY (DevCod),
    CONSTRAINT UQ_DEV_01 UNIQUE (DevLgnExt)
);

CREATE INDEX IF NOT EXISTS IDX_DEV_01 ON T_DEV (DevAudIns);
CREATE INDEX IF NOT EXISTS IDX_DEV_02 ON T_DEV (DevNme);
CREATE INDEX IF NOT EXISTS IDX_DEV_03 ON T_DEV (DevCgo, DevNme);

CREATE TABLE IF NOT EXISTS T_REL (
    RelCod INTEGER,
    RelVrs VARCHAR(255) NOT NULL,
    RelTtlCmm VARCHAR(4000),
    RelDtaPub DATETIME DEFAULT CURRENT_TIMESTAMP,
    RelAudIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    RelAudUpd DATETIME,
    RelAudDlt DATETIME,
    RelAudUsr VARCHAR(255),
    CONSTRAINT PK_REL PRIMARY KEY (RelCod),
    CONSTRAINT UQ_REL_01 UNIQUE (RelVrs)
);

CREATE INDEX IF NOT EXISTS IDX_REL_01 ON T_REL (RelAudIns);
CREATE INDEX IF NOT EXISTS IDX_REL_02 ON T_REL (RelDtaPub);

CREATE TABLE IF NOT EXISTS T_TSK (
    TskCod INTEGER,
    TskExtCod INTEGER NOT NULL,
    TskTtl VARCHAR(255) NOT NULL,
    TskDsc VARCHAR(4000),
    TskImp VARCHAR(255),
    DevCod INTEGER,
    RelCod INTEGER,
    TskAudIns DATETIME DEFAULT CURRENT_TIMESTAMP,
    TskAudUpd DATETIME,
    TskAudDlt DATETIME,
    TskAudUsr VARCHAR(255),
    CONSTRAINT PK_TSK PRIMARY KEY (TskCod),
    CONSTRAINT UQ_TSK_01 UNIQUE (TskExtCod),
    CONSTRAINT FK_TSK_01 FOREIGN KEY (DevCod) REFERENCES T_DEV (DevCod) ON DELETE SET NULL,
    CONSTRAINT FK_TSK_02 FOREIGN KEY (RelCod) REFERENCES T_REL (RelCod) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_TSK_01 ON T_TSK (TskAudIns);
CREATE INDEX IF NOT EXISTS IDX_TSK_02 ON T_TSK (TskTtl);
CREATE INDEX IF NOT EXISTS IDX_TSK_03 ON T_TSK (TskImp);
